name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Browserstack setup
            - name: 'BrowserStack Env Setup' # Invokes the setup-env action
              uses: browserstack/github-actions/setup-env@master
              with:
                  username: ${{ secrets.BROWSERSTACK_USERNAME }}
                  access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

            - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
              uses: browserstack/github-actions/setup-local@master
              with:
                  local-testing: start
                  local-identifier: random

            # Code setup
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: 'Integration test'
              run: npm run e2e:bs:test

            - name: Unit test
              run: npm run test:prod

            - name: Build
              run: npm run build

            # Terminating the BrowserStackLocal tunnel connection
            - name: 'BrowserStackLocal Stop'
              uses: browserstack/github-actions/setup-local@master
              with:
                  local-testing: stop
